# Generated by Django 3.1.5 on 2021-01-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('img_url', models.CharField(max_length=3000)),
                ('price', models.FloatField()),
            ],
        ),
    ]
